# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nopii < Formula
  desc "Pipe-first CLI for deterministic PII pseudonymization"
  homepage "https://github.com/iilei/nopii"
  version "0.1.1-pre+tap-01"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iilei/nopii/releases/download/v0.1.1-pre+tap-01/nopii_Darwin_x86_64.tar.gz"
      sha256 "705e2ad97d75d104d150e3f592749d8aca097c1bf5ab3c0c513eeb3313d6c883"

      define_method(:install) do
        bin.install "nopii"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iilei/nopii/releases/download/v0.1.1-pre+tap-01/nopii_Darwin_arm64.tar.gz"
      sha256 "0c3b5ee67e1511d9cd524a83ccd5f4c92c6a16c316bbbd68cdf1ac8f9936e901"

      define_method(:install) do
        bin.install "nopii"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iilei/nopii/releases/download/v0.1.1-pre+tap-01/nopii_Linux_x86_64.tar.gz"
      sha256 "d566c363fb361edc5174643342c1e0cecb071d786e833a22c3af457eb49fbda3"
      define_method(:install) do
        bin.install "nopii"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iilei/nopii/releases/download/v0.1.1-pre+tap-01/nopii_Linux_arm64.tar.gz"
      sha256 "3dc7932fc718ac565f0cac272b1b081f133bc77c7056a1ed3cb6df568695d700"
      define_method(:install) do
        bin.install "nopii"
      end
    end
  end

  test do
    system "#{bin}/nopii --help"
  end
end
